# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: upload jar (to workflow's artifact) 
      uses: actions/upload-artifact@v1
      with:
        name: hello-1.0-SNAPSHOT.jar
        path: target/hello-1.0-SNAPSHOT.jar
    - name: test for secret environment
      env:
         TEST_ENV: ${{ secrets.TEST_SECRET }}      
      run: echo $TEST_ENV
    - uses: jfrog/setup-jfrog-cli@v1
    - name: Test for cfrog CLI
      run: jfrog --version
    - name: build and install by jfrog
      run: |
         jfrog rt c rt-server-1 --user=admin --apikey=AKCp5fTtyDVzJPfVsWBmYWqLNa36ttb7T19Q7Y1honS49AwBW7qoPVJYw5GjTa3TrwsVzRrFB --url=http://ma2.japaneast.cloudapp.azure.com:8082/artifactory/ --interactive=false
         jfrog rt mvnc --server-id-resolve=rt-server-1 --server-id-deploy=rt-server-1 --repo-resolve-releases=libs-release --repo-deploy-releases=libs-release --repo-resolve-snapshots=libs-snapshot --repo-deploy-snapshots=libs-snapshot
         jfrog rt mvn clean install
